# Generated by Django 5.2.1 on 2025-07-16 20:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='daily_transaction_reset',
            field=models.DateField(default=django.utils.timezone.localdate, verbose_name='Daily transaction reset'),
        ),
    ]
