# Generated by Django 5.2.1 on 2025-07-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_alter_wallet_daily_transaction_reset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='paystack_card_token',
        ),
        migrations.AddField(
            model_name='card',
            name='paystack_authorization_signature',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Paystack authorization signature'),
        ),
    ]
