# Generated by Django 5.2.1 on 2025-11-12 15:36

import django.db.models.deletion
import djmoney.models.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_remove_card_paystack_card_token_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', help_text='Current balance in the wallet', max_digits=19, verbose_name='Balance'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='daily_transaction_reset',
            field=models.DateField(blank=True, help_text='Date when daily limits were last reset', null=True, verbose_name='Daily transaction reset date'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dedicated_account_bank',
            field=models.CharField(blank=True, help_text='Bank name for the dedicated account', max_length=100, null=True, verbose_name='Dedicated account bank'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='dedicated_account_number',
            field=models.CharField(blank=True, db_index=True, help_text='Virtual account number for direct deposits', max_length=50, null=True, verbose_name='Dedicated account number'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Whether the wallet is active and can perform operations', verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='is_locked',
            field=models.BooleanField(db_index=True, default=False, help_text='Locked wallets cannot perform transactions', verbose_name='Is locked'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='last_transaction_date',
            field=models.DateTimeField(blank=True, db_index=True, help_text='Date and time of the last transaction', null=True, verbose_name='Last transaction date'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='paystack_customer_code',
            field=models.CharField(blank=True, db_index=True, help_text='Paystack customer identifier', max_length=100, null=True, unique=True, verbose_name='Paystack customer code'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='tag',
            field=models.CharField(blank=True, db_index=True, help_text='A custom identifier for the wallet', max_length=100, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=models.OneToOneField(help_text='The user who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['user'], name='wallet_user_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['is_active', 'is_locked'], name='wallet_status_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['tag'], name='wallet_tag_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['paystack_customer_code'], name='wallet_paystack_idx'),
        ),
        migrations.AddIndex(
            model_name='wallet',
            index=models.Index(fields=['last_transaction_date'], name='wallet_last_txn_idx'),
        ),
    ]
